//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LikeButtonTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Research
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Research()
        {
            this.Likes = new HashSet<Like>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int ResearchId { get; set; }
        public string RName { get; set; }
        public string LAuthor { get; set; }
        public string RFile { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> LikeCount { get; set; }
        public Nullable<int> DislikeCount { get; set; }
        public Nullable<bool> SecretPoll { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Like> Likes { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
